command: ["streamlit", "run", "app.py", "--server.port", "8000", "--server.headless", "true"]
env:
  - name: DATABRICKS_SERVER_HOSTNAME
    value: host-name
  - name: DATABRICKS_HTTP_PATH
    value: /sql/1.0/warehouses/sql-warehouse
  - name: DATABRICKS_TOKEN
    valueFrom: secret
